<?php

use CRM_MoeveCrewing_ExtensionUtil as E;

return [
  'moeve_crewing_role_option_group' => [
    'name' => 'moeve_crewing_role_option_group',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'participant_role',
    'title' => E::ts('Role option group'),
    'description' => E::ts('Technical name of the option group containing available crew roles.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_candidate_role' => [
    'name' => 'moeve_crewing_candidate_role',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'potentielles Crewmitglied',
    'title' => E::ts('Candidate participant role'),
    'description' => E::ts('Technical option name used for new crew applications before a crew function is assigned.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_individual_group' => [
    'name' => 'moeve_crewing_individual_group',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'moeve_crewing_individual',
    'title' => E::ts('Individual custom group'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_participant_group' => [
    'name' => 'moeve_crewing_participant_group',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'moeve_crewing_participant',
    'title' => E::ts('Participant custom group'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_event_group' => [
    'name' => 'moeve_crewing_event_group',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'moeve_crewing_event',
    'title' => E::ts('Event demand custom group'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_event_info_group' => [
    'name' => 'moeve_crewing_event_info_group',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'moeve_crewing_event_info',
    'title' => E::ts('Event information custom group'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_capabilities_field' => [
    'name' => 'moeve_crewing_capabilities_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'faehigkeiten',
    'title' => E::ts('Capabilities field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_preferences_field' => [
    'name' => 'moeve_crewing_preferences_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'gewuenschte_funktionen',
    'title' => E::ts('Preferred roles field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_event_number_field' => [
    'name' => 'moeve_crewing_event_number_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'veranstaltungsnummer',
    'title' => E::ts('Event number field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_departure_port_field' => [
    'name' => 'moeve_crewing_departure_port_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'hafen_von',
    'title' => E::ts('Departure port field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_route_field' => [
    'name' => 'moeve_crewing_route_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'route',
    'title' => E::ts('Route field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_arrival_port_field' => [
    'name' => 'moeve_crewing_arrival_port_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'hafen_bis',
    'title' => E::ts('Arrival port field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_crew_on_board_field' => [
    'name' => 'moeve_crewing_crew_on_board_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'stamm_an_bord',
    'title' => E::ts('Crew on board field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_crew_off_board_field' => [
    'name' => 'moeve_crewing_crew_off_board_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'stamm_von_bord',
    'title' => E::ts('Crew off board field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_organizer_field' => [
    'name' => 'moeve_crewing_organizer_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'organisator',
    'title' => E::ts('Organizer field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_comment_field' => [
    'name' => 'moeve_crewing_comment_field',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'kommentar',
    'title' => E::ts('Event comment field'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_role_mapping' => [
    'name' => 'moeve_crewing_role_mapping',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'title' => E::ts('Role mapping override'),
    'description' => E::ts('Optional JSON configuration overriding the default role-to-field mapping.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_participant_status_colors' => [
    'name' => 'moeve_crewing_participant_status_colors',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'title' => E::ts('Participant status colours'),
    'description' => E::ts('JSON colour mapping keyed by stable participant status names.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_participant_status_workflow' => [
    'name' => 'moeve_crewing_participant_status_workflow',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'title' => E::ts('Participant status workflow'),
    'description' => E::ts('JSON mapping of statuses allowed for assigned crew and declined applications, including their defaults.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moeve_crewing_declined_participants' => [
    'name' => 'moeve_crewing_declined_participants',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'title' => E::ts('Declined crewing applications'),
    'description' => E::ts('Internal JSON marker for applications explicitly declined in the crewing workspace.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
];
